
var f;f=string_replace_all(global.themepath,'theme.ini',ini_read_string('Default','colorfile','theme_colors.ini'))
ini_close()

var str1,str2,str3,str4,str5,str6,str7,str8,str9;
ini_open(f)
str1=ini_read_string('Color','Color1','$FFFFFF')
str2=ini_read_string('Color','Color2','$FFFFFF')
str3=ini_read_string('Color','VisColBG','$FFFFFF')
str4=ini_read_string('Color','VisColFG','$FFFFFF')
str5=ini_read_string('Color','FloatCol',string(c_lime))
str6=ini_read_string('Color','FrontWinCol','$606060')
str7=ini_read_string('Color','FrontCapCol','$FFFFFF')
str8=ini_read_string('Color','FloatBGCol','$101010')
str9=ini_read_string('Color','FloatAlpha','255')

__frontmenucol=hex_to_col(real_hex(ini_read_string('Color','MenuCol','$FFFFFF')))
__visbgcol=hex_to_col(real_hex(ini_read_string('Color','VisualBGCol','$FFFFFF')))
__visfgcol=hex_to_col(real_hex(ini_read_string('Color','VisualFGCol','$FFFFFF')))
__butplaycol=hex_to_col(real_hex(ini_read_string('Color','PlayCol','$FFFFFF')))
__butstopcol=hex_to_col(real_hex(ini_read_string('Color','StopCol','$FFFFFF')))
__butplayrandcol=hex_to_col(real_hex(ini_read_string('Color','PlayRandCol','$FFFFFF')))
__butnextcol=hex_to_col(real_hex(ini_read_string('Color','NextCol','$FFFFFF')))
__butprevcol=hex_to_col(real_hex(ini_read_string('Color','PrevCol','$FFFFFF')))
__butaboutcol=hex_to_col(real_hex(ini_read_string('Color','AboutCol','$FFFFFF')))
__butsettcol=hex_to_col(real_hex(ini_read_string('Color','SettingsCol','$FFFFFF')))
__butpausecol=hex_to_col(real_hex(ini_read_string('Color','PauseCol','$FFFFFF')))
__butalontcol=hex_to_col(real_hex(ini_read_string('Color','AlOnTCol','$FFFFFF')))
__butaddmuscol=hex_to_col(real_hex(ini_read_string('Color','AddMusCol','$FFFFFF')))
__butvolcol=hex_to_col(real_hex(ini_read_string('Color','VolumeCol','$FFFFFF')))
__butslidecol=hex_to_col(real_hex(ini_read_string('Color','PosSlideCol','$FFFFFF')))
__butslidercol=hex_to_col(real_hex(ini_read_string('Color','SliderCol','$FFFFFF')))
__butvisualcol=hex_to_col(real_hex(ini_read_string('Color','VisualizeCol','$FFFFFF')))
__butsavelistcol=hex_to_col(real_hex(ini_read_string('Color','SaveListCol','$FFFFFF')))
__butloadlistcol=hex_to_col(real_hex(ini_read_string('Color','LoadListCol','$FFFFFF')))
__butloopcol=hex_to_col(real_hex(ini_read_string('Color','LoopCol','$FFFFFF')))
__minibutton1col=hex_to_col(real_hex(ini_read_string('Color','Mini1Col','$FFFFFF')))
__minibutton2col=hex_to_col(real_hex(ini_read_string('Color','Mini2Col','$FFFFFF')))
__minibutton3col=hex_to_col(real_hex(ini_read_string('Color','Mini3Col','$FFFFFF')))
__floatfgcol=hex_to_col(real_hex(ini_read_string('Color','FloatFGSpriteCol','$FFFFFF')))
__floatbgcol=hex_to_col(real_hex(ini_read_string('Color','FloatBGSpriteCol','$FFFFFF')))
__butsortcol=hex_to_col(real_hex(ini_read_string('Color','FloatBGSpriteCol','$FFFFFF')))
__bgcol=hex_to_col(real_hex(ini_read_string('Color','BGSpriteCol','$FFFFFF')))

global.color1=hex_to_col(real_hex(str1))
global.color2=hex_to_col(real_hex(str2))
global.visbgcol=hex_to_col(real_hex(str3))
global.visfgcol=hex_to_col(real_hex(str4))
global.floatcolor=hex_to_col(real_hex(str5))
global.frontcol=hex_to_col(real_hex(str6))
global.captioncol=hex_to_col(real_hex(str7))
global.floatbgcol=hex_to_col(real_hex(str8))
global.floatalpha=real(string_digits(str9))/255



background_color=hex_to_col(real_hex(ini_read_string('Color','bgCol','$014426')))
ini_close()
